### PR TITLE
Add support for shortened netmasks

### PR DESCRIPTION
**Pull request by kiesel**
A netmask of `192.168.0.0/24` can also be written omitting trailing zeroed parts, ie `192.168/24`.

### CODE REVIEW

**Comment by thekid** [comment]
Thanks for your PR, but it looks like this is only half of what we need: The tests - the implementation is missing, however 😀

**Comment by kiesel** [comment]
Right, I only added the test that is failing atm. I'll also contribute a fix, but I didn't have a working XP at hand at the time of writing.

**Comment by thekid** [comment]
> I didn't have a working XP at hand at the time of writing

Right, we don't have an ArchLinux package - you could try the one-line shell installer as advertised https://github.com/xp-runners/reference and install to `~/bin` or use the shell entrypoint:

```bash
$ cd ~/bin
$ curl -sSL https://baltocdn.com/xp-framework/xp-runners/distribution/downloads/e/entrypoint/xp-run-8.5.0.sh > xp
$ chmod 755 xp
```

This entrypoint is an ultra-lightweight shell script which eliminates the need for installing Mono. However, instead of being able to use subcommands like `xp test ...`, you'll have to type `xp xp.unittest.TestRunner ...`, plus you'll get none of the composer integrations.

**Comment by kiesel** [comment]
Added the fix - not sure about the failing tests, though.

**Comment by thekid** [comment]
> Added the fix - not sure about the failing tests, though.

I can reproduce them failing with local PHP 8.1-dev and will have a look into that.

image

**Comment by thekid** [comment]
Released in https://github.com/xp-framework/networking/releases/tag/v10.2.0

Thanks for your contribution @kiesel!

**Pull request merged**
